version: "3"

networks:

  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.230.0/28

services:

  database:
    image: "postgres:11"
    restart: always
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
    networks:
      - internal
    expose:
      - 5432
#    ports:
#      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  web:
    build: ./_server/web
    ports:
      - "8003:8003"
    volumes:
      - ./:/home/root/project
    depends_on:
      - database
    stdin_open: true
    tty: true
    command: "python manage.py runserver 0.0.0.0:8003"

  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./_server/nginx/conf.d:/etc/nginx/conf.d
      - ./_server/nginx/cert:/etc/letsencrypt
      - ./_server/www:/var/www
