version: "3"

networks:

  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.235.0/28

services:

  database:
    image: "postgres:11"
    restart: always
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
    networks:
      - internal
    expose:
      - 5432
#    ports:
#      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  webapp:
    build: .
    ports:
      - "8083:8083"
    volumes:
      - ./:/home/project/app
    working_dir: /home/project/app
    networks:
      - internal
    depends_on:
      - database
    stdin_open: true
    tty: true
    entrypoint: bash ./webapp-entrypoint-lite.sh

#  nginx:
#    image: nginx:1.15-alpine
#    depends_on:
#      - webapp
#    networks:
#      - internal
#    ports:
#      - '80:80'
#      - '443:443'
#    volumes:
#      - ./_server/nginx/conf.d:/etc/nginx/conf.d
#      - ./_server/nginx/cert:/etc/letsencrypt
